require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  DisplayStyleGuide: true

Documentation:
  Enabled: false

LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
